import { StyleSheet } from "react-native";
import { theme } from "./theme";

export const componentStyles = StyleSheet.create({
  topBar: {
    height: 60,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: theme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  brandTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.colors.ink,
    letterSpacing: -0.4,
  },
  pairIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: theme.colors.cardAlt,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  navHeader: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    backgroundColor: theme.colors.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
  },
  navHeaderTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.ink,
    letterSpacing: -0.3,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.colors.cardAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: "#000000",
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.emeraldSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radii.full,
    gap: 6,
  },
  pulseDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.emerald,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.colors.emerald,
    letterSpacing: 0.8,
  },
  unpairBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  unpairText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.danger,
  },
  deviceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 14,
  },
  deviceIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: theme.colors.cardAlt,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: "700",
    color: theme.colors.ink,
  },
  deviceMeta: {
    fontSize: 12,
    color: theme.colors.inkSoft,
    marginTop: 2,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: 12,
  },
  innerDivider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginLeft: 58,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toggleTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.colors.ink,
  },
  toggleDesc: {
    fontSize: 12,
    color: theme.colors.inkSoft,
    marginTop: 2,
  },
  unpairedCard: {
    alignItems: "center",
    paddingVertical: 28,
    gap: 8,
  },
  unpairedIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: theme.colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  unpairedTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.ink,
  },
  unpairedSub: {
    fontSize: 13,
    color: theme.colors.inkSoft,
    textAlign: "center",
    lineHeight: 18,
    maxWidth: 260,
    marginBottom: 10,
  },
  pairPrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.ink,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  pairPrimaryBtnText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  warningCard: {
    flexDirection: "row",
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#fed7aa",
    gap: 12,
  },
  warningIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#ffedd5",
    alignItems: "center",
    justifyContent: "center",
  },
  warningTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#9a3412",
  },
  warningDesc: {
    fontSize: 12,
    color: "#c2410c",
    lineHeight: 16,
    marginTop: 2,
  },
  permissionLink: {
    marginTop: 6,
  },
  permissionLinkText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ea580c",
  },
  section: {
    gap: 8,
  },
  sectionHeader: {
    fontSize: 11,
    fontWeight: "800",
    color: theme.colors.inkFaint,
    letterSpacing: 0.8,
    marginLeft: 4,
  },
  appListCard: {
    backgroundColor: theme.colors.card,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: "hidden",
  },
  appRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 12,
  },
  appIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  appName: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.colors.ink,
  },
  appSubtext: {
    fontSize: 11,
    color: theme.colors.inkSoft,
    marginTop: 1,
  },
  cardDesc: {
    fontSize: 12,
    color: theme.colors.inkSoft,
    lineHeight: 16,
    marginBottom: 12,
  },
  simBtnRow: {
    flexDirection: "row",
    gap: 8,
  },
  simBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    backgroundColor: theme.colors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  simBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.colors.ink,
  },
  cameraContainer: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000000",
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  finderBox: {
    width: 240,
    height: 240,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  corner: {
    position: "absolute",
    width: 24,
    height: 24,
    borderColor: theme.colors.primary,
  },
  cornerTL: {
    top: -2,
    left: -2,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 16,
  },
  cornerTR: {
    top: -2,
    right: -2,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 16,
  },
  cornerBL: {
    bottom: -2,
    left: -2,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 16,
  },
  cornerBR: {
    bottom: -2,
    right: -2,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 16,
  },
});

export const screenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.canvas,
  },
  cardContainer: {
    flex: 1,
    backgroundColor: theme.colors.card,
  },
  centerBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollContent: {
    padding: 16,
    gap: 16,
  },
  footer: {
    padding: 24,
    backgroundColor: theme.colors.card,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
  },
  hintBox: {
    alignItems: "center",
    gap: 4,
  },
  hintTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.colors.ink,
  },
  hintSub: {
    fontSize: 13,
    color: theme.colors.inkSoft,
    textAlign: "center",
    lineHeight: 18,
  },
  statusBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 8,
  },
  statusText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.ink,
  },
  errorBox: {
    backgroundColor: theme.colors.dangerSoft,
    borderRadius: 12,
    padding: 12,
  },
  errorText: {
    fontSize: 13,
    color: theme.colors.danger,
    textAlign: "center",
    fontWeight: "600",
  },
  permissionBox: {
    flex: 1,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  permissionIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: theme.colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  permTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.ink,
    textAlign: "center",
  },
  permSub: {
    fontSize: 14,
    color: theme.colors.inkSoft,
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 280,
    marginBottom: 16,
  },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.ink,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  actionBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
});
